apiVersion: v1
kind: Namespace
metadata:
  name: portal
---
apiVersion: v1
kind: Service
metadata:
  name: sms-backend-services
  namespace: portal
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backtend
  ports:
    - name: rest-api-port
      protocol: TCP
      port: 8091
      targetPort: 8091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend-services
  namespace: portal
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: enrollment-service
          image: enrollment-service:1.0
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
              name: rest-api-port
