server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: auth
  #  Configuration for MySQL Database
  datasource:
    url: jdbc:mysql://mysql:3306/portal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    
jwt:
  secretKey: ThisIsMyLocalDevelopmentSecretKeyForTestingPurposeOnly
  expirationTime: 86400000