spring:
  application:
    name: payment-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
server:
  port: 8092
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true  