spring:
  application:
    name: career-service
  sleuth:
    sampler:
      percentage: 0.1
  zipkin:
    enabled: true
    base-url: http://localhost:9411
server:
  port: 8093
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true